### PR TITLE
Add example for using DKP with CMake and VSCode

### PR DESCRIPTION
**Pull request by HorstBaerbel**
TODO:
- Add proper Windows configuration to c_cpp_properties.json.
- Add automatic debug configuration to launch.json that builds, runs the emulator and connects GDB.
- Use CMake variables in launch.json, especially for the binary.

### CODE REVIEW

**Comment by HorstBaerbel** [comment]
Before it gets lost in time, I'll just leave this here. Note that I pushed those to <incompatible project link removed>, but it has a MIT license so I included that for the subfolder. I hope this is ok with DKPs license...

**Comment by WinterMute** [comment]
Sorry, this doesn't really fit in with the way we do things.

All our examples have a standard layout that uses plain Makefiles for several reasons. We don't provide  project files for any particular IDE to avoid requiring that IDE in order to build a project. While we do have cmake toolchain files, we don't use them for examples and single platform projects. Requiring end users to have tools that aren't commonly installed is antithetical to our design philosophy.

Merging this PR would also violate the DRY principle since it contains cmake toolchain files (which, fwiw, contain really odd bodges for no readily apparent reason) See https://github.com/devkitPro/pacman-packages/tree/master/pkgbuild-scripts

This is also out of date, and has been for quite some time given that devkitARM is now using gcc 8.2.0,

**Comment by HorstBaerbel** [comment]
There's no need to use VSCode. You can use CMake from the command line. It's even documented in the README. It's also not out of date. The hardcoded 7.1.0 stuff is just for intellisense. I would upgrade it if r50 is working for me. There might be a way to use environment variables for this.
It's rough around the edges, that's why the TODOs are there...
I've been using this setup for month now, without issues other that programming errors, which are not CMakes fault...

**Comment by WinterMute** [comment]
Cmake isn't commonly installed on end user's machines and requires an extra step before building a project. We don't want vscode files or alternative cmake toolchain files, even if they didn't contain peculiar bodgery.

Whether or not you've been using it for months without issues is irrelevant. We've been down this rabbit hole several times and we're not going down it again.

**Pull request closed without merging**
